image: node:14

stages:
  - Clean
  - Test

Clean Node Modules:
  stage: Clean
  script:
    - cd engine && yarn install --silent
    - cd ../ui && yarn install --silent
  rules:
    - changes:
        - package.json
    - if: $FORCE_CLEAN == "true"

  cache:
    key:
      files:
        - yarn.lock
        - package.json
    paths:
      - node_modules/
    policy: push


Prettier Check:
  stage: Test
  script:
    - echo "Checking for prettyness"
    - cd engine && yarn run prettier:check
    - cd ../ui && yarn run prettier:check
  cache:
    key:
      files:
        - yarn.lock
        - package.json
    paths:
      - node_modules/
    policy: pull
